### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by tcetin** [ozziest/turkLirasiMaskesi#1]
Hocam bir demo koyaydın iyiydi.

**Comment by Bruskyer** [comment]
demo yok! anlatılan şekilde çalışmıyor maalesef maskmoney'e devam

**Comment by ozziest** [comment]
Bu proje aktif bir şekilde geliştirilmiyor. Bir çok hatası mevcut ve ne yazık ki düzeltebilecek zamanı bulamıyorum. Anlayışınız için teşekkür ederim.
