### ISSUE TITLE
klonlanan inputlar ile ilgili problem

### ISSUE THREAD

**Issue by uskan** [ozziest/turkLirasiMaskesi#2]
clone ve appendTo kullanarak alt alta input eklediğim bir projem var. İlk inputta turk lirası başarılı bir şekilde çalışırken klonlanan inputlarda inputlara turk lirası çalışmıyor. Bunun yanında klonlanan inputlarıda bir nevi readonly hale getirerek değer girilmesini engelliyor.

**Comment by ozziest** [comment]
Bu proje aktif bir şekilde geliştirilmiyor. Bir çok hatası mevcut ve ne yazık ki düzeltebilecek zamanı bulamıyorum. Anlayışınız için teşekkür ederim.
