### ISSUE TITLE
Android Telefonlarda Çalışmıyor

### ISSUE THREAD

**Issue by sahinersever** [ozziest/turkLirasiMaskesi#3]
Galaxy Note 8 ve Galaxy 4'te test ettim. Çalışmıyor, çözümü var mı?

**Comment by ozziest** [comment]
Bu proje aktif bir şekilde geliştirilmiyor. Bir çok hatası mevcut ve ne yazık ki düzeltebilecek zamanı bulamıyorum. Anlayışınız için teşekkür ederim.
